version: '3.8'

services:
  # Database service using PostgreSQL image
  database:
    image: postgres:latest # Use the latest PostgreSQL image from Docker Hub
    environment:
      POSTGRES_DB: akasha # Define the name of the database
      POSTGRES_USER: postgres # Define the username for accessing the database
      POSTGRES_PASSWORD: postgres # Define the password for the user
    ports:
      - '5432:5432' # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL
    volumes:
      - database:/var/lib/postgresql/data

  # Backend service
  backend:
    build: . # Build the Docker image using the Dockerfile in the current directory (backend folder)
    image: iqbalpa/backend-movies:latest
    ports:
      - '8000:8000' # Forward the container's port 8000 to the host machine's port 8000 for accessing the backend service
    depends_on:
      - database # Ensure that the backend service starts after the database service is up and running
    env_file:
      - .env

  # Frontend service
  frontend:
    build: ../frontend # Path to the frontend folder containing the Dockerfile
    image: iqbalpa/frontend-movies:latest
    ports:
      - '3000:3000' # Map the container's port 3000 to the host's port 3000
    depends_on:
      - backend # Ensure that the frontend starts after the backend is running

volumes:
  database:
    name: movies-catalog-db
